<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?= $this->headTitle(\Application\Module::TITLE)->setSeparator(' - ')->setAutoEscape(false) ?>

        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no"/>

        <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->headLink(['rel' => 'apple-touch-icon', 'href' => $this->basePath() . '/img/apple-touch-icon.png'])
            ->prependStylesheet($this->basePath('css/style.css'), 'screen,print')
            ->prependStylesheet($this->basePath('css/metromega.css'), 'screen,print')
            ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', 'screen,print')
            ->prependStylesheet('https://use.fontawesome.com/releases/v5.7.2/css/all.css', 'screen,print')
		?>
		<style type="text/css">
            body { padding-top: 0px; }
            
            .dropdown-submenu{
                position: relative;
            }
            .dropdown-submenu a::after{
                transform: rotate(-90deg);
                position: absolute;
                right: 3px;
                top: 40%;
            }
            .dropdown-submenu:hover .dropdown-menu, .dropdown-submenu:focus .dropdown-menu{
                display: flex;
                flex-direction: column;
                position: absolute !important;
                margin-top: -30px;
                left: 100%;
            }
            @media (max-width: 992px) {
                .dropdown-menu{
                    width: 50%;
                }
                .dropdown-menu .dropdown-submenu{
                    width: auto;
                }
            }
        </style>
        
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js')
            ->prependFile('https://code.jquery.com/jquery-3.3.1.slim.min.js')
        ?>
    </head>
    <body>

        <!-- BACKGROUND -->
        <img src="img/ArrigoniBridge.jpg" class="background" alt="" />
        <!-- /BACKGROUND -->

        <!-- LOGO -->
        <div class="header">
            <h1>
                <a data-scroll="scrollto" href="#start">
                    <img src="img/headerlogo.png" height="32" width="35" class="header-logo" alt=""/>
                    City of Middletown
                </a>
            </h1>
        </div>
        <!-- /LOGO -->

        <!-- MAIN CONTENT SECTION -->
        <section id="content">

            <?= $this->content ?>

        </section> 
        <!-- /MAIN CONTENT SECTION -->

        <!-- LOCKSCREEN -->
        <section class="mlightbox" id="lockscreen">
            <div id="lockscreen-content">
                <img src="img/logo.png" height="109" width="140" id="locklogo"  alt="Metromega"/>
                <br/><br/>
                <img src="img/preloader.gif" id="lockloader"  alt="Loading.."/>
            </div>
        </section>
        <!-- /LOCKSCREEN -->

        <!-- SIDEBAR -->
<!--         <div id="opensidebar"><i class="fa fa-3x">+</i></div> -->
<!--         <section id="sidebar"> -->
<!--             <ul> -->
<!--                 <li><a href="http://www.middletownct.gov" ><i class="fa fa-group fa fa-4x"></i></a></li> -->
<!--                 <li><a href="http://www.iamresponding.com"><i class="fa fa-fire fa-4x"></i></a></li> -->
<!--             </ul> -->
<!--         </section> -->
        <!-- /SIDEBAR -->

        <!-- PRELOADER -->
        <section class="mlightbox" id="loader">
            <a href="#">
                <img src="img/preloader.gif" alt="Loading.."/>
            </a>
        </section>
        <!-- /PRELOADER -->

		<?php 
		$this->InlineScript()
		  ->appendFile('https://code.jquery.com/jquery-latest.min.js')
		  ->appendFile($this->basePath() . './js/respond.min.js')
		  ->appendFile($this->basePath() . './js/jquery.isotope.min.js')
		  ->appendFile($this->basePath() . './js/jquery.mousewheel.js')
		  ->appendFile($this->basePath() . './js/jquery.mCustomScrollbar.js')
		  ->appendFile($this->basePath() . './js/tileshow.js')
		  ->appendFile($this->basePath() . './js/mlightbox.js')
		  ->appendFile($this->basePath() . './js/jquery.touchSwipe.min.js')
		  ->appendFile($this->basePath() . './js/mlightbox.js')
		  ->appendFile($this->basePath() . './js/jquery.fitVids.js')
		  ->appendFile($this->basePath() . './js/lockscreen.js')
		  ->appendFile('https://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js')
		  ->appendFile($this->basePath() . './js/script.js');
		?>
		<?= $this->inlineScript() ?>
    </body>
</html>