<?php foreach ($this->data as $section => $records) : ?>
<!-- SECTION -->
<section class="clearfix section" id="start">
	
	<!-- SECTION TITLE -->
    <h3 class="block-title"><?=$section?></h3>
    <!-- /SECTION TITLE -->

    	<?php foreach ($records as $record) : ?>
        <!-- SECTION TILES -->
        <div class="tile <?=$record['COLOR']?> w2 h1 <?=$record['TYPE']?>">
            <a class="link" target="<?=$record['TARGET']?>" href="<?=$record['URL']?>">
                <i class="<?=$record['ICON']?>"></i>
                <span class="title"><?=$record['CAPTION']?></span>
            </a>
        </div>
        <?php endforeach; ?>
	
</section>
<!-- /SECTION -->
<?php endforeach; ?>